model_list:
  - model_name: "hepsi"
    litellm_params:
      model: "openai/hepsi"
      api_base: "http://172.26.32.1:20128/v1"
      api_key: "sk-58bbadde44171bff-6jq5bl-7378c3af"

general_settings:
  master_key: "omniroute"
  port: 4000
