model_list:
  - model_name: "9router"
    litellm_params:
      model: "openai/dijitalvarlik"
      api_base: "http://172.30.0.10:20128/v1"
      api_key: "sk-5762d1405cedb9c7-vtowrm-d6ad8046"
  - model_name: "9router-mycombo"
    litellm_params:
      model: "openai/mycombo"
      api_base: "http://172.30.0.10:20128/v1"
      api_key: "sk-5762d1405cedb9c7-vtowrm-d6ad8046"
  - model_name: "9router-deepseek"
    litellm_params:
      model: "openai/deepseekcombo"
      api_base: "http://172.30.0.10:20128/v1"
      api_key: "sk-5762d1405cedb9c7-vtowrm-d6ad8046"

general_settings:
  master_key: "omniroute"
  port: 4000
